### ISSUE TITLE
Not working when using a remote server

### ISSUE THREAD

**Issue by cristianpb** [sensiml/open-gateway#28]
I want to use this app deployed in a raspberry pi as my headless remote server and controlled using my main pc. 

When I connect remotely using `http://RASPBERRY_IP:5555` the application won't work because all the API request are hard coded to request  `http://localhost:5555`.

I think that one can use relative request in the frontend and let the backend to establish the hostname using the variable SERVER_HOST.

**Comment by cdknorow** [comment]
@cristianpb  thanks for the suggestion, I'll look into updating that when I get some time. Alternatively, if you want to make a pull request for this we can add it.

**Comment by cristianpb** [comment]
Hi, I did I PR here #29 
I have been using it.
